# Features
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
TRI_LAYER_ENABLE = no

# Encoder
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# OLED
OLED_ENABLE = yes

# Per key RGB
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes

# Audio
AUDIO_ENABLE = no
MUSIC_ENABLE = no

# Haptic feedback
HAPTIC_ENABLE = no
SPLIT_HAPTIC_ENABLE = no

# Debug
CONSOLE_ENABLE = yes

